### ISSUE TITLE
Does not seem to look at .gitignores in subdirectories

### ISSUE THREAD

**Issue by nomeata** [siers/nix-gitignore#10]
`.gitignore` files can be in subdirectories; it seems that this tool does not take that into account.

**Comment by siers** [comment]
This is true, I had not thought about this.

**Comment by siers** [comment]
This patch makes the tests fail indeed. 

```diff
diff --git a/test.nix b/test.nix
index 220ba93..e48a0de 100644
--- a/test.nix
+++ b/test.nix
@@ -41,12 +41,16 @@ let
 
         touches 5-directory      {1,2,3,4,5,^,$,^$,$^,[,[[,],]],]]],ab,bb,\\,\\\\}
 
+        touches 6-recursive      a b xbx c
+
         touches 9-expected       {unfiltered,filtered-via-aux-{filter,ignore,filepath}}
     ); }
 
     create-tree "$1"
+
     cat ${builtins.toFile "nixgitignore-ignores" ignores} > "$1/.gitignore"
     cat ${builtins.toFile "nixgitignore-ignores" ignoresAux} > "$1/aux.gitignore"
+    cat ${builtins.toFile "nixgitignore-ignores" ignoresRecursive} > "$1/6-recursive/.gitignore"
   '';
 
   ignores = ''
@@ -75,6 +79,7 @@ let
   '';
 
   ignoresAux = "/9-expected/*filepath\n";
+  ignoresRecursive = "*b*";
 
   sourceUnfiltered = (runCommand "test-tree" {} ''
     mkdir -p $out; cd $out;
```

**Comment by siers** [comment]
I think the way to go would be to first traverse the tree with filterSource to make a derivation with all the gitignore files, then compile a big ignore file from those.

**Comment by siers** [comment]
@nomeata I've created the feature and it seems like it should work. I've got only a few tests on it though.

**Comment by siers** [comment]
This mostly works and is in the right direction, but there's I found an edge case yesterday (which also affects the version that doesn't look into subdirectories) that requires this to be ported to nix instead of awk to reuse some code.

**Comment by siers** [comment]
Judging by the tests, I trust this will work most of the time, therefore I am closing this.

**Comment by siers** [comment]
@nomeata I forgot to ask — did you or anyone need this? :/

**Comment by nomeata** [comment]
I ended up not using `nix-gitignore` (probably because of this feature). So if I would use it, I would need it. But I don’t.

**Comment by siers** [comment]
@offlinehacker
