### ISSUE TITLE
Simpler, more understandable API

### ISSUE THREAD

**Issue by siers** [siers/nix-gitignore#11]
In #8 @obfusk mentioned that the function names aren't too good.

I think the -`Aux` functions are at fault here, so let's rename them to `gitignoreSource` and remove the current `gitignoreSource` that doesn't take additional gitignores. Therefore the old `gitignoreSource` would have to be written as `gitignoreSource []`.

At the tiny cost of adding a variable we'd get rid of the -`Aux`, which, even though is a technically a correct name in my opinion, I do agree is not a great name.

What do you think @obfusk?

**Comment by obfusk** [comment]
I didn't have time to look at it earlier, but it looks good. Renaming the variables also makes the source a bit more easy to understand. I'm never too happy about breaking backwards compatibility, but oh well.

\- Felix
