### ISSUE TITLE
Huge increase in build times

### ISSUE THREAD

**Issue by asymmetric** [siers/nix-gitignore#12]
Hi,

I'm working on a [big repo](https://github.com/asymmetric/evm-semantics/tree/nix-gitignore) with lots of files, and using `nix-gitignore` adds something like 20 minutes to the build times.

I guess [this](https://github.com/siers/nix-gitignore/blob/221d4aea15b4b7cc957977867fd1075b279837b3/default.nix#L118-L146) part of the code is probably where we take the performance hit, as it's iterating on every file.

**Comment by siers** [comment]
Hi,

Too bad, but this is very possible. Did that do that before recursive gitignore search as well, may I ask?

The functions, however, are composable, so you should be easily able to make a filter that would only use the single gitignore file.

Maybe the recursive search shouldn't be the default.

**Comment by asymmetric** [comment]
When was recursive search introduced? I can have a look.

**Comment by siers** [comment]
#10 / 6a06a28, c0a0253, f92e62c

**Comment by siers** [comment]
The recursive part can be easily removed though. Maybe the default should be the faster version — and recursive as an option if you're really into it?
