### ISSUE TITLE
Certain file names result in a crash

### ISSUE THREAD

**Issue by mightybyte** [siers/nix-gitignore#14]
I'm getting the following error:

```
error (ignored): writing to file: Bad file descriptor
error: invalid regular expression ‘^\.stack-work/downloaded/zrAzVbT4hDDB/buildUtils/(.*/|)[^/]*\.hi’, at /nix/store/ssdx84fbg92ql3mifvwk2j6fzrnp7irg-source/default.nix:24:26
```

I discovered that if I delete the `.stack-work` directory from the project root, this error goes away.  This is a blocker for me using this package because some people on my team use stack and I can't have that breaking my build.  If it was something about how I write my `.gitignore` files, I might be able to work around it.  But it's not about that because deleting `.stack-work` fixed the problem with no change to the `.gitignore` file.

**Comment by siers** [comment]
Hi,

This regex doesn't seem to be invalid on its own. Are you using Linux or OS X? Could you maybe make a self-contained bug reproduction code / archive?

**Comment by mightybyte** [comment]
I'm on OS X.  I'll try to put together a minimal test case to reproduce.

**Comment by mightybyte** [comment]
It looks like this has something to do with the behavior when there are nested .gitignore files.  I can reproduce by cloning the following repo:

https://github.com/mightybyte/readable/tree/nix-gitignore-test

Change to the `nix-gitignore-test` branch and then do `nix-build`.  It should work fine.  Now create a directory called `foo` and then create `foo/.gitignore` with the following contents:

```
foo
.stack-work/
```

Now do `nix-build` and you should see the failure.

**Comment by siers** [comment]
Hi Doug,

`builtins.match "(.*/|)" ""` doesn't work because of https://github.com/NixOS/nix/issues/1537. `(.*/|)` and can be replaced with `(.*/)?`, which seems to be working judging by `./test.sh`.

I'll commit it soon enough.
