### ISSUE TITLE
.gitignore in parent directories

### ISSUE THREAD

**Issue by roberth** [siers/nix-gitignore#16]
The user-requested path may not be the root of the repo, in which case the ignores from (for example) the root will be ignored.

In order to implement this, we need to traverse the ancestor directories to find the repo root (dir + /.git). This can be done with `dirOf`, `readDir` to check the presence of `.gitignore` and/or `.git`.

My current workaround is to process the entire repo at once and then use its subpaths.

**Comment by siers** [comment]
An interesting idea! Though I'm not planning to implement this for now, as I'm not using this project very much any more. :)

**Comment by roberth** [comment]
:+1: When someone wants to implement this, it's probably best to refactor away the derivation, #17

**Comment by roberth** [comment]
I wrote some code that finds these files in #20 but didn't get around to the integration.

**Comment by domenkozar** [comment]
One of the drawbacks for using root repo is that all the subfolders depend on it's src hash. Haven't investigated why yet, but probably due src chaining.

**Comment by roberth** [comment]
@domenkozar this can be circumvented using something like #20. It looks for only the relevant files during evaluation, so no dependency on the whole project root is created there.

**Comment by siers** [comment]
Not planning to cover; want to reduce open issues, even though I'm not planning to actively develop this.

**Comment by roberth** [comment]
:+1: we're good with https://github.com/hercules-ci/gitignore.nix
