### ISSUE TITLE
Can import from derivation be avoided?

### ISSUE THREAD

**Issue by roberth** [siers/nix-gitignore#17]
Before burning me on the stake, I know this is not technically *import* from derivation, but *readFile* causes most of the same behavior :)

It seems to me that it's possible to achieve the goal of this library without a derivation, using `readDir` to discover files (and/or test their existence) and `readFile` to read the `.gitignore`s. Did you try this? If so, what problems did you run into?

**Comment by siers** [comment]
Hi,

I thought it would serve some purpose to create a derivation, but I'm not sure what I was thinking any more. :)

I don't think I ran in any problems with the other approach — it even might've been easier to go about it that way, since that `awk` expression is something quite ridiculous. :)

**Comment by siers** [comment]
Not planning on implementing this for the recursive version.
