### ISSUE TITLE
Escaped hashes generate incorrect regexes

### ISSUE THREAD

**Issue by expipiplus1** [siers/nix-gitignore#19]
The gitignore regex `\#` generates the following error:

```
error: invalid regular expression '(^|.*/)\#', at /nix/store/s4v09b2qhaaln7ssllk40x328w1d4mbg-source/pkgs/build-support/nix-gitignore/default.nix:26:26
```

An effective workaround is to escape the hashes using a character class `[#]`.

**Comment by fosskers** [comment]
Just hit this myself.

**Comment by LucianU** [comment]
I think my issue is related. I get this:
```
error: invalid regular expression '^(.*/|)\.eggs/.*', at /nix/store/nz3ki8viypiid9rxbiryrfr0qbqmz57v-source/default.nix:24:26
```

**Comment by fosskers** [comment]
When I pulled `/#*` out of my `.gitignore` the problem went away.

**Comment by siers** [comment]
Hm, `/#*`, `xx#*` and `xx\#*` patterns seem to work just fine for me on NixOS droplet, nix (Nix) 2.2.2 with `nix-gitignore` master.

**Comment by siers** [comment]
`\#*` too!

**Comment by siers** [comment]
Can reopen if able to reproduce still.
