### ISSUE TITLE
Doesn't work with trailing slashes

### ISSUE THREAD

**Issue by colehaus** [siers/nix-gitignore#2]
gitignore supports declarations with trailing slashes and will only match these patterns against directories. For example:

```
.stack-work/
```

`nix-gitignore` seems to implement these patterns improperly and these directories end up present among the source files during nix builds.

**Comment by siers** [comment]
That was indeed missing, thank you very much.

**Comment by siers** [comment]
@colehaus Does it work as expected?

**Comment by colehaus** [comment]
Yup, thanks!
