### ISSUE TITLE
Always filter .git/ directory

### ISSUE THREAD

**Issue by Profpatsch** [siers/nix-gitignore#22]
The most important piece of filtering is not done currently, removing the `.git/` subdirectory.

**Comment by srghma** [comment]
have this issue too

**Comment by Profpatsch** [comment]
@srghma Can you PR this fix to the [nixpkgs version of nix-gitignore](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/nix-gitignore/default.nix) and CC me? That would be great.

**Comment by srghma** [comment]
@Profpatsch  done (almost forgot)

**Comment by Profpatsch** [comment]
Awesome, thanks.
