### ISSUE TITLE
Suggestion: use lib.cleanSourceWith instead of builtins.filterSource

### ISSUE THREAD

**Issue by kolloch** [siers/nix-gitignore#27]
Thank you, great lib. I am using the version in nixpkgs but thought that reporting the suggestion here is probably more appropriate.

I am running into a situation where I need to prefilter the source so before passing it to `gitignoreSource`. Unfortunately. nix-gitignore uses `builtins.filterSource` directly and not `lib.cleanSourceWith`. That means that if sources are prefiltered by [`cleanSourceWith`](https://github.com/NixOS/nixpkgs/blob/master/lib/sources.nix#L38-L68), the prefiltered sources are actually instantiated in the nix store -- exactly what I would like to prevent.

I think, this is easy to fix and I can provide a PR if you are interested. Except, of course, you have a good reason for the current behavior that I am not aware of!

**Comment by siers** [comment]
No, there's no reason that I'm aware of. You can make a PR, I would merge
it. However https://github.com/hercules-ci/gitignore.nix claims to use
cleanSourceWith, so maybe that solves your problems.

Also getting it back into nixpkgs is a PITA that I don't have the time or
the reason to do anymore. :(

**Comment by kolloch** [comment]
> However https://github.com/hercules-ci/gitignore.nix claims to use cleanSourceWith, so maybe that solves your problems. Also getting it back into nixpkgs is a PITA that I don't have the time or the reason to do anymore. :(

This sounds a bit like you don't really want to maintain this anymore (no blame from my side, I can imagine a thousand reasons for this) and you consider gitignore.nix a likely successor?

**Comment by kolloch** [comment]
Ok, I'll use gitignore.nix :)
