### ISSUE TITLE
Integration into Nix/Nixpkgs

### ISSUE THREAD

**Issue by CMCDragonkai** [siers/nix-gitignore#6]
I was wondering if this can either:

1. Be contributed directly into nixpkgs, or
2. Be installed as a nix package that is then importable locally? (I've never seen a package like that, but it would be essentially a Nix expression that is packaged as a Nix package).

**Comment by siers** [comment]
Yeah, I was wondering about this too. I wouldn't mind either approach, so I
guess I just have to consult #nixos about this and send them a PR.

**Comment by siers** [comment]
Or maybe an issue on github would also work, since not everyone has time or
frequents for IRC.

**Comment by siers** [comment]
Hey @CMCDragonkai, I want to add some motivation in the README.md, so the nixpkgs maintainers would like this more. Do you mind sharing how you use this project?

**Comment by CMCDragonkai** [comment]
I'm not currently using it because it's not in nixpkgs and I find it difficult to add another dependency.

**Comment by siers** [comment]
✔️ 🎉

**Comment by utdemir** [comment]
I think it's worth updating README to point to `pkgs.nix-gitignore`. I just spent some time using `callPackage (fetchFromGitHub ...)` only to figure out I can just do `pkgs.nix-gitignore`.

**Comment by siers** [comment]
I thought I'd wait for a release, but ok I'll update it sooner. :)

**Comment by siers** [comment]
@utdemir :confetti_ball:
