### ISSUE TITLE
gitignoreFilterSourceAux adds .gitignore twice

### ISSUE THREAD

**Issue by obfusk** [siers/nix-gitignore#8]
`gitignoreFilterSourceAux` uses:
```nix
let aux' = lib.toList aux ++ [(root + "/.gitignore")];
```
to add the `.gitignore` and then calls `gitignoreFilterSourcePure` which calls `gitignoreCompileIgnore` which does the same again:
```nix
aux_list = lib.toList aux ++ [(root + "/.gitignore")];
```

As a result of this, `gitignoreSourcePure` effectively does not differ from `gitignoreSourceAux`.
To be honest, the naming of the functions doesn't really help me figure out what the difference was intended to be, but I assume `gitignoreSourcePure` was maybe not supposed to read the `.gitignore`?

\- Felix

**Comment by siers** [comment]
Yeah, that really was the case! I've added a test case that failed before and now is fixed! :)

The names really aren't that great indeed. Haven't put so much thought into this, so maybe you can propose something.

**Comment by obfusk** [comment]
Naming things is notoriously hard. The "Usage" in the readme helps. I'll let you know if I come up with anything.

\- Felix
